'''
Contains classes for electric field reconstruction
from Stark-split Rydberg EIT spectra 

Author: Mykhailo Vorobiov
'''
#%%
from typing import Callable, Dict
from numpy.typing import NDArray

import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

from lmfit import minimize, Parameters, fit_report

from pinqued_tools.spectroscopy.spectrum import SpectralData, Axes0D
from pinqued_tools.spectroscopy.lineshapes import HoltsmarkLine
from pinqued_tools.spectroscopy.field_reference import FieldReference

class SignalSimulator():
    '''
    Class that based on the Rydberg levels Stark splitting 
    from generated by the `FieldReference` class simulates EIT spectra.
    '''
    def __init__(self, 
                 reference: FieldReference,
                 lineshape_func: Callable|None = None
                 ):
        self._reference = reference
        self._lineshape_func = lineshape_func

        if lineshape_func is None:
            print('No lineshape function provided, using Holtsmark lineshape by default.')
            self._hline_list = self._holtsmark_spectrum_prepare()
            print(len(self._hline_list))

    @property
    def hline_list(self):
        if self._hline_list is None:
            print(f'Holtsmark lines not prepared.') 
        return self._hline_list

    def _holtsmark_spectrum_prepare(self) -> list[HoltsmarkLine]:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        line_keys = self._reference.level_labels
        efield_reference = self._reference.efield
        stark_reference = self._reference.detunings[line_keys[0]]
        
        hline_list = []
        for key in line_keys:
             print(f'Preparing Holtsmark line for {key}...')
             stark_reference = self._reference.detunings[key]
             hline = HoltsmarkLine(efield_reference, stark_reference)
             # 1. Define your 4D parameter space
             freq_grid = np.linspace(-1200, 400, 300)  # <-- The frequency axis for the LUT
             efield_grid = np.linspace(0.0, 80.0, 100)
             E0_grid = np.linspace(1e-5, 2.0, 20)
             width_grid = np.linspace(20.0, 50.0, 10)  # <-- The new dimension
             hline.build_lut(freq_grid, efield_grid, E0_grid, width_grid, base_model='2d')
             hline_list.append(hline)
             print(f'Finished preparing Holtsmark line for {key}.')

        print(f'Ready to simulate spectra with Holtsmark spectrum! Number of lines {len(hline_list)}')
        return hline_list

    def holtsmark_spectrum(self, 
                           freq: NDArray, 
                           params: Parameters
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        efield = params['efield'].value
        scale_factor = params['amp'].value
        width = params['width'].value
        Hfield = params['E0'].value
        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(self._hline_list))]
        spectrum = np.zeros_like(freq)
        for hline, ai in zip(self._hline_list, r_amp):
            spectrum += hline(freq, efield, width, Hfield, ai)
        spectrum *= scale_factor
        return spectrum

    def holtsmark_spectrum_bg(self, 
                           freq: NDArray, 
                           params: Parameters
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        '''
        signal = self.holtsmark_spectrum(freq, params)
        bg = self.bg_drifts(freq, params, poly_terms=2)
        spectrum = signal + bg
        return spectrum

    def signal(self, 
               freq: NDArray, 
               params: Parameters,
               **kwargs) -> NDArray[np.float64]:
        '''
        Simulate EIT signal for a given electric field
        '''
        scale_factor = params['amp'].value
        width_0 = params['width_0'].value
        gradE_dr = params['gradE_dr'].value
        efield = params['efield'].value

        ref = self._reference.interp(efield)

        spectrum = np.zeros_like(freq)
        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(ref))]
        for (fpos, df_de), amp in zip(ref, r_amp):
            width = width_0  - df_de * gradE_dr
            spectrum += amp * self._lineshape_func(freq, fpos, width, **kwargs)
        spectrum *= scale_factor
        return spectrum
    
    def bg_drifts(self, 
                  freq: NDArray, 
                  params: Parameters,
                  poly_terms: int = 2,
                  **kwargs):
        coefs = [params[f'b{i}'].value for i in range(poly_terms) if params[f'b{i}'] is not None]
        poly = np.poly1d(coefs)
        if len(coefs) < poly_terms:
            return np.zeros_like(freq)
        return poly(freq)

    def signal_with_bg(self, 
                       freq: NDArray, 
                       params: Parameters,
                       poly_terms: int = 3,
                       **kwargs) -> NDArray[np.float64]:
        signal = self.signal(freq, params, **kwargs)
        bg = self.bg_drifts(freq, params, poly_terms=poly_terms)
        return signal + bg

    def signal_with_bg_shifted(self, 
                       freq: NDArray, 
                       params: Parameters,
                       poly_terms: int = 3,
                       **kwargs) -> NDArray[np.float64]:
        f_shifted = freq - params['f_shift'].value
        signal = self.signal(f_shifted, params, **kwargs)
        bg = self.bg_drifts(f_shifted, params, poly_terms=poly_terms)
        return signal + bg
    
class GPPoissonSignalSimulator1D(SignalSimulator):
    def __init__(self, 
                 reference: FieldReference,
                 px_size: float,
                 lineshape_func: Callable|None = None
                 ):
        super().__init__(reference, lineshape_func)
        self.px_size = px_size

    def holtsmark_spectrum(self, 
                           freq: NDArray, 
                           params: Parameters,
                           efield: float|None = None,
                           grad_vec: float|None = None,
                           E0: float|None = None,
                           amp: float|None = None,
                           n_subsamples: int = 20
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        Can accept spatial arrays for efield and grad_vec to vectorize the calculation.
        '''

        scale_factor = params['amp'].value if amp is None else amp
        width = params['width'].value
        
        grad_correct = params['grad_correct'].value if 'grad_correct' in params else 0.0
        if grad_vec is not None:
            # Transverse gradient modeled as proportional to local E-field
            grad_val = np.sqrt(grad_vec**2 + (grad_correct * efield)**2)
        else:
            grad_val = grad_correct * efield

        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(self._hline_list))]
        
        # Handle 1D (spatial) evaluation
        if efield is not None and np.ndim(efield) > 0:
            spectrum = np.zeros((len(efield), len(freq)))
        else:
            spectrum = np.zeros_like(freq, dtype=np.float64)
        
        for i, (hline, ai) in enumerate(zip(self._hline_list, r_amp)):
            if n_subsamples > 1:
                hline_smeared = 0.0
                # Use Gauss-Legendre quadrature for accurate sub-pixel integration
                points, weights = np.polynomial.legendre.leggauss(n_subsamples)
                # Map domain from [-1, 1] to [-0.5, 0.5] and normalize weights to sum to 1
                offsets = points * 0.5
                norm_weights = weights * 0.5
                for offset, weight in zip(offsets, norm_weights):
                    # Ensure absolute efield to prevent negative LUT queries
                    # Fixed dimensionality bug: px_size instead of px_size**2
                    efield_smear = np.abs(efield + (grad_val * self.px_size * offset))
                    hline_smeared += weight * hline(freq, efield=efield_smear, width=width, E0=E0, amplitude=ai, model='lut')
            else:
                hline_smeared = hline(freq, efield=np.abs(efield), width=width, E0=E0, amplitude=ai, model='lut')
            spectrum += hline_smeared 
        spectrum *= scale_factor
        return spectrum

    def holtsmark_spectrum_bg(self, 
                           freq: NDArray, 
                           params: Parameters,
                           efield: float|NDArray|None = None,
                           grad_vec: float|NDArray|None = None,
                           E0: float|NDArray|None = None,
                           b_coefs: list[float]|None = None,
                           poly_terms: int = 2,
                           amp: float|None = None
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape
        with a polynomial (tilted) background drift.
        '''
        signal = self.holtsmark_spectrum(freq, params, efield=efield, grad_vec=grad_vec, E0=E0, amp=amp)
        
        if b_coefs is not None:
            coefs = b_coefs
        else:
            # Safely extract polynomial background coefficients if they exist
            coefs = [params[f'b{i}'].value if f'b{i}' in params else 0.0 for i in range(poly_terms)]
            
        poly = np.poly1d(coefs)
        
        return signal + poly(freq)
    
class GPPoissonSignalSimulator1D_widthGrid(GPPoissonSignalSimulator1D):
    def __init__(self, 
                 reference: FieldReference,
                 px_size: float,
                 lineshape_func: Callable|None = None
                 ):
        super().__init__(reference, lineshape_func)
        self.px_size = px_size
        

    def holtsmark_spectrum(self, 
                           freq: NDArray, 
                           params: Parameters,
                           efield: float|NDArray|None = None,
                           grad_vec: float|NDArray|None = None,
                           E0: float|NDArray|None = None,
                           amp: float|NDArray|None = None,
                           n_subsamples: int = 3
                           ) -> NDArray:
        '''
        Simulate EIT signal for a given electric field using the Holtsmark lineshape.
        Uses spatially varying width array constructed from width_weight{i} parameters.
        '''
        scale_factor = params['amp'].value if amp is None else amp

        grad_correct = params['grad_correct'].value if 'grad_correct' in params else 0.0
        if grad_vec is not None:
            # Transverse gradient modeled as proportional to local E-field
            grad_val = np.sqrt(grad_vec**2 + (grad_correct * efield)**2)
        else:
            grad_val = grad_correct * efield

        # Handle 1D (spatial) evaluation
        if efield is not None and np.ndim(efield) > 0:
            nx = len(efield)
            spectrum = np.zeros((nx, len(freq)))
            width = np.array([params[f'width_weight{i}'].value for i in range(nx)])
        else:
            spectrum = np.zeros_like(freq, dtype=np.float64)
            width = params['width_weight0'].value if 'width_weight0' in params else params['width'].value

        r_amp = [params[f'rel_amp_{i}'].value for i in range(len(self._hline_list))]
        
        for i, (hline, ai) in enumerate(zip(self._hline_list, r_amp)):
            if n_subsamples > 1:
                hline_smeared = 0.0
                # Use Gauss-Legendre quadrature for highly accurate sub-pixel integration
                points, weights = np.polynomial.legendre.leggauss(n_subsamples)
                # Map domain from [-1, 1] to [-0.5, 0.5] and normalize weights to sum to 1
                offsets = points * 0.5
                norm_weights = weights * 0.5
                for offset, weight in zip(offsets, norm_weights):
                    # Ensure absolute efield to prevent negative LUT queries
                    efield_smear = np.abs(efield + grad_val * self.px_size * offset)
                    hline_smeared += weight * hline(freq, efield=efield_smear, width=width, E0=E0, amplitude=ai, model='lut')
            else:
                hline_smeared = hline(freq, efield=np.abs(efield), width=width, E0=E0, amplitude=ai, model='lut')
            spectrum += hline_smeared 
        spectrum *= scale_factor
        return spectrum

#%%
if __name__=='__main__':
    pass

# %%
